[[platinum]]
name = "Element"
website = "https://element.io"
logo = "element.svg"

[[gold]]
name = "Beeper"
website = "https://beeper.com"
logo = "beeper.svg"

[[silver]]
name = "Fairkom"
website = "https://www.fairkom.eu/"
logo = "fairkom.svg"

[[silver]]
name = "Famedly"
website = "https://www.famedly.com/"
logo = "famedly.svg"

[[silver]]
name = "Fractal Networks"
website = "https://github.com/fractalnetworksco/"
logo = "fractal-networks.svg"

[[silver]]
name = "Gematik"
website = "https://www.gematik.de/"
logo = "gematik.png"

[[silver]]
name = "IndieHosters"
website = "https://indie.host"
logo = "indiehosters.png"

[[silver]]
name = "XWiki"
website = "https://www.xwiki.org/"
logo = "xwiki.png"

[[ecosystem]]
name = "Conduit"
website = "https://conduit.rs/"
logo = "conduit.svg"

[[ecosystem]]
name = "Draupnir"
website = "https://github.com/the-draupnir-project/Draupnir"
logo = "draupnir.png"

[[ecosystem]]
name = "Nheko-Reborn"
website = "https://nheko.im/nheko-reborn/nheko/"
logo = "nheko.svg"

[[ecosystem]]
name = "Thunderbird"
website = "https://thunderbird.net/"
logo = "thunderbird.svg"

[[ecosystem]]
name = "Trixnity"
website = "https://trixnity.gitlab.io/trixnity"
logo = "trixnity.png"

[[associate]]
name = "Eclipse Foundation"
website = "https://eclipse.org"
logo = "eclipse.svg"

[[associate]]
name = "GNOME Foundation"
website = "https://gnome.org"
logo = "gnome.svg"

[[associate]]
name = "KDE e.V."
website = "https://kde.org"
logo = "kde.svg"